package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Curso;
import model.CursoAluno;

/**
 *
 * @author Matheus Assunção <matheus.tba@hotmail.com>
 */
public class JFrameAlunosEdicao extends JFrameBase {

    /**
     * Creates new form JFrameAlunosEdicao
     */
    private static JFrameAlunosEdicao sInstance;
    private Aluno _aluno = new Aluno();
    List<Curso> l_curso = new ArrayList();
    List<CursoAluno> l_cursosAdicionados = new ArrayList();
    List<CursoAluno> l_cursosExcluidos = new ArrayList();
    private final DefaultTableModel Grid;
    
    public JFrameAlunosEdicao() throws ClassNotFoundException {
        initComponents();
        inicializaComponente(this);
        this.Grid = (DefaultTableModel) gridCursosAdicionados.getModel();
        carregarCursos();
    }

     public static JFrameAlunosEdicao getInstance() throws ClassNotFoundException {
        return sInstance = new JFrameAlunosEdicao();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        comboCurso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAddCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridCursosAdicionados = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Novo Aluno");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Curso");

        btnAddCurso.setText("Adicionar");
        btnAddCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCursoActionPerformed(evt);
            }
        });

        gridCursosAdicionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gridCursosAdicionados);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setVisible(false);
        try {
            JFrameAlunos.getInstance().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAddCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCursoActionPerformed
        if (podeAdicionarCurso()) {
            l_cursosAdicionados.add(
                        new CursoAluno(0, _aluno.getCodigo(), ((Curso) comboCurso.getSelectedItem()).getCodigo(), ((Curso) comboCurso.getSelectedItem()).getDescricao())
                    );
            atualizarGrid();
        }
    }//GEN-LAST:event_btnAddCursoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (gridCursosAdicionados.getSelectedRow() >= 0 && l_cursosAdicionados.size() > 0) {
            if (l_cursosAdicionados.get(gridCursosAdicionados.getSelectedRow()).getCodigo() > 0) {
                l_cursosExcluidos.add(l_cursosAdicionados.get(gridCursosAdicionados.getSelectedRow()));   
            }
            l_cursosAdicionados.remove(gridCursosAdicionados.getSelectedRow());
            atualizarGrid();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum item está selecionado.", "Excluir curso", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (podeGravar()) {
            _aluno.setNome(txtNome.getText());
            try {
                Aluno.insertOrUpdateData(_aluno, l_cursosAdicionados, l_cursosExcluidos);
                setVisible(false);
                JFrameAlunos.getInstance().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private boolean podeGravar() {
        boolean ret = true;
        if (ret && txtNome.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            txtNome.requestFocus();
            ret = false;
        }
        return ret;
    }
    
    private boolean podeAdicionarCurso() {
        boolean ret = true;
        if (ret && comboCurso.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum curso está selecionado.", "Adicionar curso", JOptionPane.ERROR_MESSAGE); 
            ret = false;
        }
        if (ret) {
            for (int i = 0; i < l_cursosAdicionados.size(); i++) {
                if (l_cursosAdicionados.get(i).getCodigoCurso() == ((Curso) comboCurso.getSelectedItem()).getCodigo()) {
                    JOptionPane.showMessageDialog(null, "O aluno já está matriculado neste curso.", "Adicionar curso", JOptionPane.ERROR_MESSAGE); 
                    ret = false;
                }                
            }
        }
        return ret;
    }
    
    public void novoAluno() {
        setTitle("Teste VR Software - Novo Aluno");
        lbTitulo.setText("Novo Aluno");
        _aluno.setCodigo(0);
        setVisible(true);
    }
    
    public void alterarAluno(Aluno aluno) throws ClassNotFoundException, SQLException {
        CursoAluno dao_cursoAluno = new CursoAluno();
        _aluno = aluno;
        setTitle("Teste VR Software - " + _aluno.getNome());
        lbTitulo.setText(_aluno.getNome());
        txtNome.setText(_aluno.getNome());
        l_cursosAdicionados = dao_cursoAluno.getDataByAluno(_aluno.getCodigo());
        atualizarGrid();
        setVisible(true);
    }
    
    private void atualizarGrid() {
        Grid.setNumRows(0);
        for (int i = 0; i < l_cursosAdicionados.size(); i++) {
            Grid.addRow(new Object[] {l_cursosAdicionados.get(i).getDescricaoCurso()});   
        }
    }
    
    private void carregarCursos() throws ClassNotFoundException {
        Curso dao_curso = new Curso();
        l_curso = dao_curso.getData();
        comboCurso.removeAllItems();
        comboCurso.addItem(new Curso(0, "Selecione", ""));   
        for (int i = 0; i < l_curso.size(); i++) {
            comboCurso.addItem(l_curso.get(i));   
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameAlunosEdicao().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFrameAlunosEdicao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCurso;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Object> comboCurso;
    private javax.swing.JTable gridCursosAdicionados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables


}
